---
kind: Service
apiVersion: v1
metadata:
  labels:
    k8s-app: zookeeper-dev
  name: zookeeper-dev
  namespace: shipformula-dev
spec:
  type: NodePort
  ports:
  - name: zookeeper2181
    port: 2181
    targetPort: 2181
    nodePort: 2181
  selector:
    app: zookeeper-dev

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: zookeeper-dev
  namespace: shipformula-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zookeeper-dev
  template:
    metadata:
      labels:
        app: zookeeper-dev
    spec:
      nodeSelector:
        type: node120
      containers:
      - name: zookeeper-dev
        image: wurstmeister/zookeeper
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 2181

---
kind: Service
apiVersion: v1
metadata:
  labels:
    k8s-app: kafka-dev
  name: kafka-dev
  namespace: shipformula-dev
spec:
  type: NodePort
  ports:
  - name: kafka9092
    port: 9092
    targetPort: 9092
    nodePort: 9092
  selector:
    app: kafka-dev

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-dev
  namespace: shipformula-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-dev
  template:
    metadata:
      labels:
        app: kafka-dev
    spec:
      nodeSelector:
        type: node120
      containers:
      - name: kafka-dev
        image: wurstmeister/kafka:2.12-2.5.0
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 9092
        env:
        - name: KAFKA_ADVERTISED_PORT
          value: "9092"
        - name: KAFKA_BROKER_ID
          value: "0"
        - name: KAFKA_ZOOKEEPER_CONNECT
          value: "zookeeper-dev:2181"
        - name: KAFKA_ADVERTISED_HOST_NAME
          value: "10.103.187.126"