apiVersion: v1
kind: ConfigMap
metadata:
  name: logstash-configmap
  namespace: test-k8s
data:
  logstash.yml: |
    http.host: "0.0.0.0"
    path.config: /usr/share/logstash/pipeline
  logstash.conf: |
    # Sample Logstash configuration for creating a simple
    # Beats -> Logstash -> Elasticsearch pipeline.

    input {
      beats {
        port => 5044
      }
      tcp { 
            codec => "json_lines"
            port => 5050
            type => "tcp-input"
      }
    }

    output {
      elasticsearch {
        index => "log4jstcp-%{appname}-%{+YYYY.MM.dd}"
        hosts => [ "${ES_HOSTS}" ]
        user => "${ES_USER}"
        password => "${ES_PASSWORD}"
        cacert => '/etc/logstash/certificates/ca.crt'
      }
    }

---
kind: Service
apiVersion: v1
metadata:
  labels:
    k8s-app: test-k8s-logstash
  name: test-k8s-logstash
  namespace: test-k8s
spec:
  type: NodePort
  ports:
  - name: test-k8s-logstash
    port: 5050
    nodePort: 5050
  selector:
    app: logstash

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: logstash
  namespace: test-k8s
spec:
  replicas: 1
  selector:
    matchLabels:
      app: logstash
  template:
    metadata:
      labels:
        app: logstash
    spec:
      containers:
      - name: logstash
        image: logstash:7.16.2
        imagePullPolicy: IfNotPresent
        env:
        - name: ES_HOSTS
          value: "https://ela-es-http:9200"
        - name: ES_USER
          value: "elastic"
        - name: ES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: ela-es-elastic-user
              key: elastic
        ports:
        - containerPort: 5050
          name: logstash
        volumeMounts:
        - name: logstash-conf
          mountPath: /usr/share/logstash/config
        - name: logstash-pipeline
          mountPath: /usr/share/logstash/pipeline
        - name: cert-ca
          mountPath: "/etc/logstash/certificates"
          readOnly: true
      volumes:
      - name: logstash-conf
        configMap:
          name: logstash-configmap
          items:
          - key: logstash.yml
            path: logstash.yml
      - name: logstash-pipeline
        configMap:
          name: logstash-configmap
          items:
          - key: logstash.conf
            path: logstash.conf
      - name: cert-ca
        secret:
          secretName: ela-es-http-certs-public