apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: elk-local-storage
provisioner: kubernetes.io/no-provisioner
reclaimPolicy: Retain
volumeBindingMode: WaitForFirstConsumer

---
apiVersion: v1 
kind: PersistentVolume 
metadata: 
 name: elk-pv 
spec: 
 capacity: 
   storage: 100Gi 
 volumeMode: Filesystem 
 accessModes: 
 - ReadWriteOnce 
 persistentVolumeReclaimPolicy: Retain 
 storageClassName: elk-local-storage
 local: 
   path: /run/desktop/mnt/host/f/nfs/elk
 nodeAffinity: 
   required: 
     nodeSelectorTerms: 
     - matchExpressions: 
       - key: kubernetes.io/hostname 
         operator: In 
         values: 
         - docker-desktop

---
apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: ela
  namespace: test-k8s
spec:
  version: 7.16.2
  nodeSets:
    - name: master
      count: 1
      podTemplate:
        spec:
          initContainers:
          - name: install-plugins
            command:
            - sh
            - -c
            - |
              bin/elasticsearch-plugin install --batch https://code.shipformula.com/huliqun/elkplugin/uploads/809cb80dfaa648a2cd75c110e13641b0/elasticsearch-analysis-ik-7.16.2.zip; bin/elasticsearch-plugin install --batch https://code.shipformula.com/huliqun/elkplugin/uploads/f4050bba0698d81bc6efd498a9653acb/elasticsearch-analysis-pinyin-7.16.2.zip
      config:
        node.master: true
        node.data: true
        node.ingest: true
        node.store.allow_mmap: false
      volumeClaimTemplates:
        - metadata:
            name: elasticsearch-data
          spec:
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: 100Gi
            storageClassName: elk-local-storage
---
apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: kibana
  namespace: test-k8s
spec:
  version: 7.16.2
  count: 1
  elasticsearchRef:
    name: ela
  podTemplate:
    spec:
      containers:
      - name: kibana
